### PR TITLE
Pre-release for the null safety migration of this package.

### PR DESCRIPTION
**Pull request by ilap**
Hi,

I migrated this package to the null safety and therefor would be nice if you could update the package in `pub.dev`.

Thx in advance for your help.

Cheers,

Pal

### CODE REVIEW

**Comment by acoutts** [comment]
@dspicher any estimate when this will be published? I have a package which consumes this one and I can't migrate until this one does.

**Comment by ilap** [comment]
> @dspicher any estimate when this will be published? I have a package which consumes this one and I can't migrate until this one does.
I have decided to go /wo Hex package implementing a simple hex coder utils what you can use, see details below.

``` dart
class HexCoder implements Encoder {
  const HexCoder._singleton();
  static const HexCoder instance = HexCoder._singleton();

  static const _alphabet = '0123456789abcdef';
  static const _hexMap = <String, int>{
    '0': 0x0, '1': 0x1, '2': 0x2, '3': 0x3, // 4-5
    '4': 0x4, '5': 0x5, '6': 0x6, '7': 0x7,
    '8': 0x8, '9': 0x9, 'a': 0xa, 'b': 0xb,
    'c': 0xc, 'd': 0xd, 'e': 0xe, 'f': 0xf,
    'A': 0xa, 'B': 0xb, 'C': 0xc, 'D': 0xd,
    'E': 0xe, 'F': 0xf,
  };

  static List<int> _decode(String hexString) {
    if (hexString.length % 2 != 0) {
      throw Exception(
          'Invalid `length`. Expected even number got `${hexString.length}`');
    }

    var startsWithHexStart = hexString.startsWith('0x');
    if (startsWithHexStart && hexString.length == 2) {
      throw Exception('There is no any character in the hexadecimal string');
    }

    final startIndex = startsWithHexStart ? 2 : 0;
    var result = List<int>.filled((hexString.length - startIndex) ~/ 2, 0);

    for (var x = 0, i = startIndex; i < hexString.length; i += 2, x++) {
      final left = _hexMap[hexString[i]] ?? -1;
      final right = _hexMap[hexString[i + 1]] ?? -1;

      if (left < 0 || right < 0) {
        final invalidChar = left < 0 ? hexString[i] : hexString[i + 1];
        throw Exception('The `$invalidChar` character is undefined in hex');
      }

      result[x] = (left << 4) | right;
    }

    return result;
  }

  static String _encode(List<int> hexArray, {bool withHexString = false}) {
    if (hexArray.isEmpty) {
      return '';
    }

    var result = withHexString ? '0x' : '';

    hexArray.forEach((element) {
      result += _alphabet[(element & 0xff) >> 4] + _alphabet[element & 0x0f];
    });

    return result;
  }

  @override
  String encode(Uint8List data) {
    return _encode(data);
  }

  @override
  ByteList decode(String data) {
    return ByteList(_decode(data));
  }
}
```

**Comment by haarts** [comment]
I've just looked into this and version solving fails. It is ultimately dependent on this issue: https://github.com/dart-lang/core/issues/269

**Comment by haarts** [comment]
Regarding the hex package: I briefly looked into that as well and frankly I'm hesitant to introduce the additional code. I'm hoping he hex package updates. Let's see, first we need to wait until the earlier mentioned issues is resolved.

**Comment by acoutts** [comment]
> Regarding the hex package: I briefly looked into that as well and frankly I'm hesitant to introduce the additional code. I'm hoping he hex package updates. Let's see, first we need to wait until the earlier mentioned issues is resolved.

Hey @haarts is there any way we can take the PR here and publish a new hex package that is migrated? It seems like it's being ignored / unmaintained as this PR has been open for 3 months now: https://github.com/stevenroose/dart-hex/pull/3

Perhaps we can take @ilap's fork and publish a new `dart_hex` package which is migrated, so that bech32 can migrate too.

**Comment by haarts** [comment]
I agree this is annoying. I'm a little hesitant to fork the hex package. Perhaps taking in the code is not such a bad idea after all. Ill have a good look next week!

**Comment by acoutts** [comment]
Woohoo! Looking forward to it. If that snippet above is really all that is needed from hex, it doesn't seem so bad to just cut/paste it in, with the risk hex is never updated / maintained in the future.

**Comment by acoutts** [comment]
Hey @haarts any updates?

**Comment by haarts** [comment]
Good of you to ping me. I really really try next week

**Comment by kw2019ltd** [comment]
..

**Comment by haarts** [comment]
The hex package seems alive: https://github.com/stevenroose/dart-hex/pull/3#issuecomment-791965885

**Comment by haarts** [comment]
I've just confirmed that this PR works with the updated hex package. When that lands we can update this PR and bump the version.

**Comment by stevenroose** [comment]
I just released hex v0.2.0 with null safety support.

**Comment by haarts** [comment]
Merged via 74e31744c582f0dffbc6c3c3b599e149fc890c55

**Pull request closed without merging**
